# Generated by Django 4.0.4 on 2022-06-02 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1654150473/default_fltufw.webp', max_length=255, verbose_name='image'),
        ),
    ]
